### ISSUE TITLE
Question- Removing Items

### ISSUE THREAD

**Issue by brexmania123** [PMMPPlugin/InventoryMonitor#2]
Hi so i was wondering if this is an Inventory plugin that you can remove items from a player without needing to use /clear or something on the item? I have been searching for a plugin like this so that way i can remove a banned item a player might find if it was like dropped or given to them.

**Comment by PresentKim** [comment]
This plugin is not BANITEM plugin.
It just viewer for player's inventory. (easy and synchronous)

**Comment by brexmania123** [comment]
-_- i was wondering if you could interact with the inventory not using a ban item plugin -_-
